version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./opa/policies:/policies
    command:
      - "run"
      - "--server"
      - "/policies"

  backend:
    build: ./backend
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - OPA_URL=http://opa:8181
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
      - opa
      - microservice

  microservice:
    build: ./microservice
    environment:
      - OPA_URL=http://opa:8181
    ports:
      - "6000:6000"
    depends_on:
      - opa

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak
